spring:
  datasource:
    url: jdbc:mysql://localhost:3306 # database in local
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8002
