spring:
  datasource:
    #    The database in Render has been suspended, contact me to resume database
    url: jdbc:postgresql://dpg-cvnpf224d50c73d1u7og-a.oregon-postgres.render.com:5432/car_showroom # database in Render
    driver-class-name: org.postgresql.Driver
    username: tuantran
    password: GKaL5wjNq2Ft7uPda46xPZSBGiyaFSP0
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.springframework.web: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR

jwt:
  secret: "ugvYK5hZ3VgH7TkQk4uqSefMwC37U94NO1+AxdlzJM7esgoXjApDmjOg3X6+sOz9"
  expiration: 180000

cloudinary:
  cloud-name: dtfj3any4
  api-key: 779544184462517
  api-secret: o4SKsVYt7L-JIS10-8-cUXGiqkM

server:
  port: 8090
  shutdown: immediate
