spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3307/car-showroom} # database in docker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # use_attribute_order: true # Sort column by alphabet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: "cNdOiK0ggz77Svs34Y/Wg0CweqnLUi0WQacHsBfLO/0c67s8Bqrugr/iYf0jZo52"
  expiration: 180000

cloudinary:
  cloud-name: dtfj3any4
  api-key: 779544184462517
  api-secret: o4SKsVYt7L-JIS10-8-cUXGiqkM

server:
  port: 8080
  shutdown: immediate

#jackson:
#  time-zone: Asia/Ho_Chi_Minh
#  serialization:
#    write-dates-as-timestamps: false

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /v3/api-docs

#    DataSource-Proxy
#    net:
#      ttddyy:
#        dsproxy:
#          listener: debug

