spring:
  datasource:
    url: jdbc:mysql://localhost:3307/car-showroom # database in docker
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # use_attribute_order: true # Sort column by alphabet
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

jwt:
  secret: "cNdOiK0ggz77Svs34Y/Wg0CweqnLUi0WQacHsBfLO/0c67s8Bqrugr/iYf0jZo52"

server:
  port: 8001
