# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven and MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: samin/mysql-action@v1
        ports:
          - 3800:3306  # Port on the host: 3800, Port inside the container: 3306
        env:
          MYSQL_ROOT_PASSWORD: Admin@123  # MySQL root password
          MYSQL_DATABASE: car_showroom  # Specify the database name you want to create
          MYSQL_USER: root  # Use root user directly
          MYSQL_PASSWORD: Admin@123  # MySQL password for the root user

    strategy:
      matrix:
        java: [17, 21, 23]
    env:
      CI: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ matrix.java }}'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql -h 127.0.0.1 -P 3800 -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1" &>/dev/null; do
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL is ready!"

      - name: Check and create database if needed
        run: |
          DB_EXISTS=$(mysql -h 127.0.0.1 -P 3800 -u root -p$MYSQL_ROOT_PASSWORD -e "SHOW DATABASES LIKE 'car_showroom';")
          if [ -z "$DB_EXISTS" ]; then
            echo "Database 'car_showroom' does not exist. Creating it now..."
            mysql -h 127.0.0.1 -P 3800 -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE car_showroom;"
          else
            echo "Database 'car_showroom' already exists."
          fi

      # Build project with Maven
      - name: Build with Maven
        run: mvn -B package --file CarShowroom/pom.xml

      # Update dependency graph
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # Run tests
      - name: Run tests
        run: mvn test
